### PR TITLE
Renamed event_manager to match doctrine-orm-module configuration

### PR DESCRIPTION
**Pull request by masarliev**

### CODE REVIEW

**Comment by DASPRiD** [comment]
This is a BC break which we cannot merge before the next major release.

**Comment by asgrim** [comment]
@DASPRiD version `1.0.0` hasn't been released yet, I don't see a problem with merging this before `1.0.0`?

**Review by asgrim — APPROVED** [review]

**Comment by stefanotorresi** [comment]
👎 
- it doesn't add any value at all
- it introduces inconsistency with the `entity_manager` service name, and *every other config key* for that matter, which are all in snake_case. `eventmanager` would be the only one without the separator.
- there is no actual need to bring a convention from another package that is not actually a dependency, but just loosely inspired to. I also think that this was in fact a mistake on `doctrine-orm-module` part, and it has been kept for BC, so you would basically import a wrong convention.

**Comment by asgrim** [comment]
@stefanotorresi interesting points made! I guess this is for @DASPRiD to decide as it's his lib...

**Comment by DASPRiD** [comment]
@stefanotorresi had valid points, and I totally agree with them. Let's stick with what we have.

**Pull request closed without merging**
